### ISSUE TITLE
在中国大陆如何复现该研究？

### ISSUE THREAD

**Issue by YuboFeng2023** [ArrogantL/ChatGPT4CausalReasoning#2]
您好，

对您的研究非常感兴趣。但因为OpenAI的政策封锁，导致我们想要复现您的研究非常困难。
即便您在 “output_by_ChatGPT” 文件夹中已经提供了 ChatGPT 的回复内容，但这并不全面。
所以，想向您咨询在中国大陆访问OpenAI api 的具体方法。

谢谢！

**Comment by ArrogantL** [comment]
这可能是一个政策上非常敏感的问题，超出了我们的实验结果本身。个人认为您去知乎、微博等中国大陆的社交平台进行咨询是很有希望获得答案的。
