### ISSUE TITLE
It is hard to reproduce the results

### ISSUE THREAD

**Issue by YuboFeng2023** [ArrogantL/ChatGPT4CausalReasoning#3]
Hi,

Thanks for your paper and code!
I am trying to reproduce your main results on the Table 1. But I found it is hard to reproduce the same results:
Firstly, ChatGPT is evolving, the best model on ECI task, text-davinci-003, has been closed by ChatGPT [link](https://platform.openai.com/docs/deprecations/2023-07-06-gpt-and-embeddings). 
Therefore, I turn to use OpenAI`s recommended replacement, gpt-3.5-turbo-instruct. 
But I found the F1 value of ESC has dropped from 45.9 to 35.3, even though I use the same codes with you.

Secondly, the relative stable model, gpt-3.5-turbo, is also can not to reproduce.
I use gpt-3.5-turbo-0125 to reproduce the results on ESC dataset by your code.
Bu I found the  F1 value has dropped from 41.0 to 36.2.

I follow your hyper-parameter settings, like temperature is 0, etc.

My question is:
1. ChatGPT is evolving, so how to follow your works?
2. ChatGPT is unreproducible, so how to give my contributions on your foundations?

Thank you! Could you please give some advises?

**Comment by ArrogantL** [comment]
的确 chatgpt这种闭源api 的复现实验受制于官方提供的版本。  尽管当时做实验的时间距现在已经比较久了，实验结果的绝对数值会有改变，但是个人认为论文里总结的那些趋势应该是不会变的。 从研究的角度你最好用较新的版本来进行，比如gpt3.5-1106。此外考虑使用的除openai的其他大模型来进心测试。这样更容易找到idea发论文。


如果是单纯想复现出我们论文里的实验结果，我觉得可以考虑这几个因素，首先是gpt3.5版本换成其他的试试，其次esc你是否排除了开发集？（最后两个topic的数据属于开发集）

如果你是想在此论文的基础上开展进一步研究，我建议关注论文总结的那些结论而且绝对数值。例如如果改进chatgpt，让他能够更谨慎的进行因果推理，进行方法开发类的研究。或者进一步挖掘因果幻觉问题的原因，开展实验分析性的工作。或者在此基础上提出新的因果数据集，识别大模型因果推理的弱点，分析原因，也是可以探究的路线。

**Comment by YuboFeng2023** [comment]
谢谢大佬耐心且细致的回复！
