### ISSUE TITLE
ModuleNotFoundError: No module named 'json'

### ISSUE THREAD

**Issue by Floyd-dpj** [ArrogantL/ChatGPT4CausalReasoning#4]
作者你好，ModuleNotFoundError: No module named 'json'  你好我运行此代码，报错少了json模块，是不是少上传了一个模块，希望给予解答，谢谢

**Comment by ArrogantL** [comment]
json 直接安装就好了。 pip install json。是一个非常常见的数据处理库。有安装问题也可以百度一下，应该帖子很多

**Comment by ArrogantL** [comment]
我认为该问题已经被解答，我会关闭该问题。
